version: '3.8'

services:
  thor:
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/thor
    ports:
      - 18080:8080
    build:
      context: .
      dockerfile: src/Thor.Service/Dockerfile
    container_name: thor
    depends_on:
      - ai-rabbitmq
      - ai-redis
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - DBType=postgresql # sqlite | [postgresql,pgsql] | [sqlserver,mssql] | mysql
      - ConnectionStrings:DefaultConnection=Host=ai-postgres;Port=5432;Database=aidotnet;Username=aidotnet;Password=aidotnet
      - ConnectionStrings:LoggerConnection=Host=ai-postgres;Port=5432;Database=aidotnet-log;Username=aidotnet;Password=aidotnet
      - CACHE_TYPE=Redis
      - CACHE_CONNECTION_STRING=ai-redis
      - RabbitMQ:ConnectionString=amqp://admin:admin@ai-rabbitmq:5672
      - OTEL_SERVICE_NAME=Thor
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - RunMigrationsAtStartup=true

  postgres:
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/postgres:17
    container_name: ai-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aidotnet
      POSTGRES_PASSWORD: aidotnet
      POSTGRES_DB: aidotnet
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  ai-redis:
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/redis
    container_name: ai-redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    container_name: aspire-dashboard
    ports:
      - "18888:18888"
    environment:
      - TZ=Asia/Shanghai
      - Dashboard:ApplicationName=Aspire


  ai-rabbitmq:
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/rabbitmq:3-management
    container_name: ai-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
